import 'dart:io';

import 'package:budget_buddy/core/theme/app_colors.dart';
import 'package:budget_buddy/core/theme/app_theme.dart';
import 'package:budget_buddy/data/local/hive_storage.dart';
import 'package:budget_buddy/data/models/category.dart';
import 'package:budget_buddy/data/models/transaction_item.dart';
import 'package:budget_buddy/data/repositories/category_repository.dart';
import 'package:budget_buddy/data/repositories/transaction_repository.dart';
import 'package:budget_buddy/modules/dashboard/dashboard_controller.dart';
import 'package:budget_buddy/modules/dashboard/dashboard_view.dart';
import 'package:budget_buddy/modules/dashboard/widgets/summary_card.dart';
import 'package:budget_buddy/services/app/settings_service.dart';
import 'package:budget_buddy/services/local/local_store_service.dart';
import 'package:budget_buddy/utils/date_utils.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:hive/hive.dart';

/// F-04 AC-D020-1 (D-020) — the Spent card only paints an overspend verdict
/// when there is an income to overspend.
///
/// The old condition was `spent > income` with no guard on income itself, so a
/// user who tapped "Skip for now" at onboarding (income 0 — reachable on every
/// fresh install) saw their FIRST expense turn the card error-red. P3: a colour
/// is a claim, and that claim was generated by a question the user declined to
/// answer.
///
/// Both directions are asserted, because the tempting one-line fix — dropping
/// the comparison, or clamping it — would take the red away from the case that
/// legitimately earns it.
void main() {
  final thisMonth = AppDateUtils.getCurrentMonthKey();

  int yearOf(String m) => int.parse(m.split('-')[0]);
  int monthOf(String m) => int.parse(m.split('-')[1]);

  Category food() => Category(
        id: 'food',
        name: 'Food',
        budgetLimitMinor: 500000,
        colorValue: 0xFF2D8B8B,
        iconCodePoint: Icons.restaurant.codePoint,
        month: thisMonth,
        createdAt: DateTime(2026, 1, 1, 9),
        updatedAt: DateTime(2026, 1, 1, 9),
      );

  TransactionItem expense(int amountMinor) {
    final when = DateTime(yearOf(thisMonth), monthOf(thisMonth), 3, 12);
    return TransactionItem(
      id: 'e$amountMinor',
      categoryId: 'food',
      amountMinor: amountMinor,
      note: 'Biryani',
      date: when,
      createdAt: when,
      updatedAt: when,
    );
  }

  late Directory tempDir;
  late SettingsService settings;

  setUpAll(() {
    if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(CategoryAdapter());
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(TransactionItemAdapter());
    }
  });

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('buddgetbuddy_spent');
    Hive.init(tempDir.path);
    await HiveStorage.openSettings();
    Get.put<LocalStoreService>(await LocalStoreService().init());
    Get.put(CategoryRepository());
    Get.put(TransactionRepository());
    settings = Get.put(SettingsService());
    await settings.setCurrency('PKR', '₨');
    await settings.setCurrentMonth(thisMonth);
    await Get.find<CategoryRepository>().addCategories([food()]);
    Get.put(DashboardController(
      categoryRepo: Get.find<CategoryRepository>(),
      transactionRepo: Get.find<TransactionRepository>(),
      settings: settings,
    ));
  });

  tearDown(() async {
    Get.reset();
    await Hive.deleteFromDisk();
    await Hive.close();
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  DashboardController ctrl() => Get.find<DashboardController>();

  /// Real Hive writes, so every caller wraps this in `tester.runAsync`.
  Future<void> seed({
    required int incomeMinor,
    required int spendMinor,
  }) async {
    await settings.setMonthlyIncomeMinor(incomeMinor);
    if (spendMinor > 0) {
      await Get.find<TransactionRepository>()
          .addTransaction(expense(spendMinor));
    }
  }

  /// The Spent card as it is actually built, not a re-derivation of its rule.
  Color spentCardColour(WidgetTester tester) => tester
      .widgetList<SummaryCard>(find.byType(SummaryCard))
      .firstWhere((card) => card.label == 'Spent')
      .color;

  Future<void> pumpDashboard(WidgetTester tester) async {
    await tester.pumpWidget(
        MaterialApp(theme: AppTheme.light, home: const DashboardView()));
    await tester.pumpAndSettle();
  }

  group('AC-D020-1 — income 0 is an unanswered question, not a budget of 0',
      () {
    testWidgets('income 0 with an expense logged: the Spent card is normal',
        (tester) async {
      await tester.runAsync(() => seed(incomeMinor: 0, spendMinor: 45000));
      await pumpDashboard(tester);

      expect(ctrl().totalSpentMinor, 45000);
      expect(spentCardColour(tester), AppColors.warning,
          reason: 'the user skipped the income question; nothing about ₨450 of '
              'spend makes it an overspend');
      expect(spentCardColour(tester), isNot(AppTheme.light.colorScheme.error));
    });

    testWidgets('the predicate itself withholds the verdict at income 0',
        (tester) async {
      await tester.runAsync(() => seed(incomeMinor: 0, spendMinor: 45000));

      expect(ctrl().spendExceedsKnownIncome, isFalse);
    });
  });

  group('AC-D020-1 — a real overspend still reads as one', () {
    testWidgets('income 1,000 with 1,500 spent: the Spent card is error',
        (tester) async {
      await tester
          .runAsync(() => seed(incomeMinor: 100000, spendMinor: 150000));
      await pumpDashboard(tester);

      expect(spentCardColour(tester), AppTheme.light.colorScheme.error,
          reason: 'income is known and it was exceeded — this is the claim the '
              'colour is FOR');
      expect(ctrl().spendExceedsKnownIncome, isTrue);
    });

    testWidgets('spending exactly the income is not an overspend',
        (tester) async {
      // The boundary the old code also got right, pinned so the D-020 rewrite
      // cannot quietly turn `>` into `>=`.
      await tester
          .runAsync(() => seed(incomeMinor: 100000, spendMinor: 100000));
      await pumpDashboard(tester);

      expect(spentCardColour(tester), AppColors.warning);
      expect(ctrl().spendExceedsKnownIncome, isFalse);
    });

    testWidgets('income known, spend inside it: normal', (tester) async {
      await tester
          .runAsync(() => seed(incomeMinor: 15000000, spendMinor: 45000));
      await pumpDashboard(tester);

      expect(spentCardColour(tester), AppColors.warning);
    });
  });
}
