import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../services/auth_service.dart';
import '../../services/google_auth_service.dart';
import '../../services/user_session_service.dart';
import '../../services/user_service.dart';
import '../../services/budget_service.dart';
import '../../services/income_service.dart';
import '../../services/ai_insights_service.dart';
import '../../services/ai_alert_service.dart';
import '../../services/gemini_service.dart';
import '../../data/storage/hive_service.dart';
import '../../routes/app_routes.dart';

class AuthController extends GetxController {
  final AuthService _authService = Get.find<AuthService>();
  final GoogleAuthService _googleAuthService = Get.find<GoogleAuthService>();
  final UserSessionService _userSessionService = Get.find<UserSessionService>();
  final UserService _userService = Get.find<UserService>();

  // Removed UI-specific controllers to prevent GlobalKey collisions and state duplication
  // These should now be managed by the View (StatefulWidget) or ephemeral controllers.

  final RxBool isLoading = false.obs;

  // Note: Password visibility toggle is local UI state, but if shared, can be here.
  // For simplicity, we'll keep the logic but expect Views to handle their own visibility state or use a separate controller.
  // Actually, let's keep isPasswordVisible for now if Views use it, but Views should ideally manage it.
  final RxBool isPasswordVisible = false.obs;

  @override
  void onInit() {
    super.onInit();
    // Listen to auth state changes
    _authService.authStateChanges.listen(_handleAuthStateChanged);
  }

  @override
  void onClose() {
    // Controllers generated by Views are disposed by Views.
    super.onClose();
  }

  /// Handle auth state changes
  Future<void> _handleAuthStateChanged(User? user) async {
    if (user != null) {
      // User is logged in
      try {
        await _userSessionService.initializeUserSession(user.uid);

        // Ensure user profile exists in Firestore
        await _userService.createUserProfile(user);

        // Initialize data services that depend on Hive boxes
        _initializeDataServices();

        // Check if user has completed setup (currency selection)
        if (HiveService.hasSelectedCurrency()) {
          Get.offAllNamed(AppRoutes.dashboard);
        } else {
          Get.offAllNamed(AppRoutes.currencySelection);
        }
      } catch (e) {
        Get.snackbar(
          'Error',
          'Failed to load user data: $e',
          snackPosition: SnackPosition.BOTTOM,
        );
        // Force logout if data load fails to avoid stuck state
        await logout();
      }
    } else {
      // User is logged out
      await _clearDataServices();
      await _userSessionService.clearUserSession();
      Get.offAllNamed(AppRoutes.login);
    }
  }

  /// Initialize data services (Budget, Income, etc.)
  void _initializeDataServices() {
    if (!Get.isRegistered<BudgetService>()) {
      Get.put(BudgetService(), permanent: true);
    }
    if (!Get.isRegistered<IncomeService>()) {
      Get.put(IncomeService(), permanent: true);
    }
    if (!Get.isRegistered<AiInsightsService>()) {
      Get.put(AiInsightsService(), permanent: true);
    }
    if (!Get.isRegistered<AiAlertService>()) {
      Get.put(AiAlertService(), permanent: true);
    }
    if (!Get.isRegistered<GeminiService>()) {
      Get.put(GeminiService(), permanent: true);
    }
  }

  /// Clear data services
  Future<void> _clearDataServices() async {
    await Get.delete<BudgetService>(force: true);
    await Get.delete<IncomeService>(force: true);
    await Get.delete<AiInsightsService>(force: true);
    await Get.delete<AiAlertService>(force: true);
    await Get.delete<GeminiService>(force: true);
  }

  void togglePasswordVisibility() {
    isPasswordVisible.toggle();
  }

  /// Login with Email & Password
  Future<void> login(String email, String password) async {
    try {
      isLoading.value = true;
      await _authService.signInWithEmailPassword(
        email: email,
        password: password,
      );
    } catch (e) {
      Get.snackbar(
        'Login Failed',
        e.toString(),
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Get.theme.colorScheme.error,
        colorText: Get.theme.colorScheme.onError,
        margin: const EdgeInsets.all(16),
      );
    } finally {
      isLoading.value = false;
    }
  }

  /// Sign Up with Email & Password
  Future<void> signup(String name, String email, String password) async {
    try {
      isLoading.value = true;
      await _authService.signUpWithEmailPassword(
        email: email,
        password: password,
      );

      // Update display name if provided
      if (name.isNotEmpty) {
        await _authService.currentUser?.updateDisplayName(name);
      }
    } catch (e) {
      Get.snackbar(
        'Sign Up Failed',
        e.toString(),
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Get.theme.colorScheme.error,
        colorText: Get.theme.colorScheme.onError,
        margin: const EdgeInsets.all(16),
      );
    } finally {
      isLoading.value = false;
    }
  }

  /// Login with Google
  Future<void> loginWithGoogle() async {
    try {
      isLoading.value = true;
      await _googleAuthService.signInWithGoogle();
    } catch (e) {
      Get.snackbar(
        'Google Sign-In Failed',
        e.toString(),
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Get.theme.colorScheme.error,
        colorText: Get.theme.colorScheme.onError,
        margin: const EdgeInsets.all(16),
      );
    } finally {
      isLoading.value = false;
    }
  }

  /// Logout
  Future<void> logout() async {
    try {
      isLoading.value = true;
      await _googleAuthService.signOutGoogle();
      await _authService.signOut();
    } catch (e) {
      Get.snackbar(
        'Logout Failed',
        e.toString(),
        snackPosition: SnackPosition.BOTTOM,
      );
    } finally {
      isLoading.value = false;
    }
  }

  /// Input Validators
  String? validateEmail(String? value) {
    if (value == null || value.isEmpty) {
      return 'Please enter your email';
    }
    if (!GetUtils.isEmail(value)) {
      return 'Please enter a valid email';
    }
    return null;
  }

  String? validatePassword(String? value) {
    if (value == null || value.isEmpty) {
      return 'Please enter your password';
    }
    if (value.length < 6) {
      return 'Password must be at least 6 characters';
    }
    return null;
  }

  void goToSignup() {
    Get.toNamed(AppRoutes.signup);
  }

  void goToLogin() {
    Get.back();
  }
}
