// `show debugPrint` only: foundation also exports a `Category`
// annotation, which would collide with our model.
import 'package:flutter/foundation.dart' show debugPrint;
import 'package:get/get.dart';
import '../../data/models/category.dart';
import '../../data/models/transaction_item.dart';
import '../../data/repositories/category_repository.dart';
import '../../data/repositories/transaction_repository.dart';
import '../../services/app/settings_service.dart';
import '../../utils/app_clock.dart';
import '../../utils/date_utils.dart';

class DashboardController extends GetxController {
  final CategoryRepository categoryRepo;
  final TransactionRepository transactionRepo;
  final SettingsService settings;

  DashboardController({
    required this.categoryRepo,
    required this.transactionRepo,
    required this.settings,
  });

  final categories = <Category>[].obs;
  final transactions = <TransactionItem>[].obs;

  // Every total below is in integer minor units — exact addition, no float
  // accumulator (C4).

  int get totalBudgetMinor =>
      categories.fold(0, (sum, c) => sum + c.budgetLimitMinor);

  int get totalSpentMinor => transactions
      .where((t) => _isCurrentMonth(t))
      .fold(0, (sum, t) => sum + t.amountMinor);

  int get remainingMinor => settings.monthlyIncomeMinor.value - totalSpentMinor;

  /// Whether the Spent card is entitled to paint an overspend verdict (D-020).
  ///
  /// The comparison it guards is exact — int against int — but it was being
  /// made against an income of **0**, which every fresh install can reach by
  /// tapping "Skip for now" at onboarding. The first expense then turned the
  /// Spent card error-red: a verdict generated by a question the user
  /// deliberately declined to answer. **P3 — a colour is a claim**, and a claim
  /// needs a fact behind it; a zero income is the absence of one, not a budget
  /// of nothing.
  ///
  /// Income 0 therefore reads as "unknown", never as "you have overspent". The
  /// figure itself is unchanged (F-01 AC-4 unaffected) — only whether the card
  /// is allowed to editorialise about it.
  ///
  /// This closes ONE of the six income-zero surfaces danish inventoried
  /// (`03-screen-states.md` §6). The other five — including a `-₨450`
  /// "Remaining" in red two cards to the right, and the 0.0% savings rate —
  /// are D-010, deferred by name because they need a design rather than a
  /// patch. Deliberately NOT generalised here: inventing a shared "income is
  /// unknown" rule across six surfaces from inside a one-line fix is how the
  /// deferred design gets pre-empted by an accident.
  bool get spendExceedsKnownIncome {
    final income = settings.monthlyIncomeMinor.value;
    return income > 0 && totalSpentMinor > income;
  }

  /// A ratio, not money: `int / int` is a `double` in Dart.
  double get savingsRate {
    final income = settings.monthlyIncomeMinor.value;
    if (income <= 0) return 0;
    return ((income - totalSpentMinor) / income * 100).clamp(0, 100);
  }

  int spentForCategoryMinor(String categoryId) => transactions
      .where((t) => t.categoryId == categoryId && _isCurrentMonth(t))
      .fold(0, (sum, t) => sum + t.amountMinor);

  bool _isCurrentMonth(TransactionItem t) =>
      AppDateUtils.getMonthKeyFromDate(t.date) == settings.currentMonth.value;

  /// True when the dashboard is showing the month the user is actually living
  /// in, as opposed to one they browsed back to.
  ///
  /// Three separate pieces of copy hang off this answer — whether the forward
  /// chevron is inert, whether the budgets card says "This Month's" or names
  /// the month, and whether the second summary card claims money is
  /// "Remaining" (a promise about the future) or merely "Unspent" (a fact
  /// about a month that already ended). Asked once so they cannot disagree.
  /// Through [AppClock], like every other "what month is it now" read: a debug
  /// month override that the rollover obeyed but this predicate did not would
  /// leave the harness showing "September 2026's Budgets" and the BUG-102
  /// suppression on a month the app had just rolled INTO — a screen no real
  /// user can ever see, which is the opposite of evidence.
  bool get isViewingCurrentMonth =>
      settings.currentMonth.value == AppClock.nowMonthKey();

  /// True when the month on screen is not the current one AND holds no
  /// transactions at all.
  ///
  /// Its one consumer is the summary block: on such a month "Monthly Income
  /// ₨45,000 · Spent ₨0 · Unspent ₨45,000" applies TODAY's income figure to a
  /// period the app knows nothing about, and volunteers a money claim about it
  /// ("in July you earned ₨45,000 and spent none of it") — reachable by every
  /// new user on day one (BUG-102). "Holds no records" rather than "predates
  /// first use" on purpose: browsing back WRITES categories into a month via
  /// `ensureMonth`, so the app cannot durably tell when it was installed, and
  /// the record-count predicate also covers "installed in June, logged nothing
  /// in June", which produces the identical bad screen.
  ///
  /// Count-based, never sum-based: a month whose rows happen to total zero is
  /// not an empty month. (A ₨0 transaction cannot be saved today — the amount
  /// validator refuses it — but the predicate does not lean on that.)
  ///
  /// Deliberately beside [isViewingCurrentMonth]: the "Unspent" relabel and this
  /// suppression must never disagree about which month is which.
  bool get viewedMonthHasNoRecords =>
      !isViewingCurrentMonth && !transactions.any(_isCurrentMonth);

  /// How many rows the dashboard's Recent card shows. Five: enough to prove
  /// the last few logs landed, few enough to stay above the fold.
  static const int recentLimit = 5;

  /// The newest few transactions of the VIEWED month, for the Recent card.
  ///
  /// Month-scoped like every other number on this screen — an all-time list
  /// under a month-scoped Spent figure is the mismatch F-04 exists to close, so
  /// a back-dated row appears on its own month's dashboard and nowhere else.
  /// `watchTransactions` already sorts newest first, so this only takes.
  List<TransactionItem> get recentTransactions =>
      transactions.where(_isCurrentMonth).take(recentLimit).toList();

  @override
  void onInit() {
    super.onInit();
    categoryRepo.getCategories().listen(
      (list) {
        categories.assignAll(
            list.where((c) => c.month == settings.currentMonth.value).toList());
      },
      onError: (Object e, StackTrace s) {
        // The local store swallows read failures and re-emits the last
        // good snapshot, so this should never fire — but every listener
        // carries onError so a future failing source cannot kill the
        // stream silently (H2).
        debugPrint('[DashboardController] category stream failed: $e\n$s');
      },
    );
    transactionRepo.getTransactions().listen(
      (list) => transactions.assignAll(list),
      onError: (Object e, StackTrace s) {
        // The local store swallows read failures and re-emits the last
        // good snapshot, so this should never fire — but every listener
        // carries onError so a future failing source cannot kill the
        // stream silently (H2).
        debugPrint('[DashboardController] transaction stream failed: $e\n$s');
      },
    );
  }

  /// `Future<void>`, not `void`, although both chevrons are wired straight to a
  /// `VoidCallback` (`dashboard_view.dart:37,40` — a `Future<void> Function()`
  /// satisfies it). Returning the future is what lets a test await the switch
  /// instead of guessing how many frames it takes, and it stops the work being
  /// a fire-and-forget whose failure has nowhere to land.
  Future<void> goToPreviousMonth() =>
      _switchMonth(AppDateUtils.getPreviousMonthKey(settings.currentMonth.value));

  Future<void> goToNextMonth() =>
      _switchMonth(AppDateUtils.getNextMonthKey(settings.currentMonth.value));

  /// The dashboard half of D-025 — the same roll-then-ensure pair the splash
  /// and the resume hook run, and until now the only one of the three that was
  /// still unguarded on a path a user can reach by tapping.
  ///
  /// Unguarded, a Hive write failure here produced a header naming a month
  /// whose categories were never cloned, with nothing said. That is the one
  /// outcome AC-D025-3 forbids: the header and the body must never disagree
  /// about which month the app is actually in.
  ///
  /// Both halves are inside the guard, and both are reported, because BOTH are
  /// visible on the next frame — a failed `setCurrentMonth` leaves the header
  /// on the month the user just tapped away from (a chevron that did nothing),
  /// and a failed `ensureMonth` moves the header onto a month showing "No
  /// categories yet" on a populated app. This is a user action, unlike
  /// `HomeController.handleResume`, which stays deliberately silent because
  /// nothing the user asked for failed.
  ///
  /// [_refreshCategories] runs either way, outside the catch: whatever month
  /// actually got persisted is the month the list must show. Skipping it after
  /// a failure is what would leave last month's categories under this month's
  /// header.
  Future<void> _switchMonth(String month) async {
    try {
      await settings.setCurrentMonth(month);
      await categoryRepo.ensureMonth(month);
    } catch (e, stack) {
      debugPrint('[DashboardController] month switch to $month failed: '
          '$e\n$stack');
      // Owner-approved mobile convention (2026-07-28): user-visible failures
      // surface via Get.snackbar. Copy states what is true now, never "try
      // again later" (L2).
      Get.snackbar(
        'Could not switch months',
        'Your data is safe. This month may be missing its categories — the '
            'header shows the month you are actually in.',
        snackPosition: SnackPosition.BOTTOM,
      );
    }
    _refreshCategories();
  }

  void _refreshCategories() {
    categoryRepo.getCategories().first.then(
      (list) {
        categories.assignAll(
            list.where((c) => c.month == settings.currentMonth.value).toList());
      },
      // A `then` without this is an unhandled async error (H2).
      onError: (Object e, StackTrace s) {
        debugPrint('[DashboardController] category refresh failed: $e\n$s');
      },
    );
  }
}
